// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsSRTVLPX8v6VqX1cTd5haigc54PW9yHY',
    appId: '1:155902281799:web:82da4061f33b66b18e8962',
    messagingSenderId: '155902281799',
    projectId: 'smart-manufacturing-app',
    authDomain: 'smart-manufacturing-app.firebaseapp.com',
    storageBucket: 'smart-manufacturing-app.firebasestorage.app',
    measurementId: 'G-FQ9NC41PDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvlbseUYLxtumIJcR1Ylnf-9SRQCgSsNk',
    appId: '1:155902281799:android:06be7642e983dabb8e8962',
    messagingSenderId: '155902281799',
    projectId: 'smart-manufacturing-app',
    storageBucket: 'smart-manufacturing-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW95Dpnw07Wcb6L94x8qQeaim22XUmERA',
    appId: '1:155902281799:ios:1a60a153fcf7f8d78e8962',
    messagingSenderId: '155902281799',
    projectId: 'smart-manufacturing-app',
    storageBucket: 'smart-manufacturing-app.firebasestorage.app',
    androidClientId: '155902281799-rqkp1nbd6paa1tb4demk7jdl383mcbbk.apps.googleusercontent.com',
    iosClientId: '155902281799-r2mjcaa1o5oruptv7mb4lds8pk5urvlc.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartManufacturing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW95Dpnw07Wcb6L94x8qQeaim22XUmERA',
    appId: '1:155902281799:ios:1a60a153fcf7f8d78e8962',
    messagingSenderId: '155902281799',
    projectId: 'smart-manufacturing-app',
    storageBucket: 'smart-manufacturing-app.firebasestorage.app',
    androidClientId: '155902281799-rqkp1nbd6paa1tb4demk7jdl383mcbbk.apps.googleusercontent.com',
    iosClientId: '155902281799-r2mjcaa1o5oruptv7mb4lds8pk5urvlc.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartManufacturing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsSRTVLPX8v6VqX1cTd5haigc54PW9yHY',
    appId: '1:155902281799:web:563ed5d710b55ce08e8962',
    messagingSenderId: '155902281799',
    projectId: 'smart-manufacturing-app',
    authDomain: 'smart-manufacturing-app.firebaseapp.com',
    storageBucket: 'smart-manufacturing-app.firebasestorage.app',
    measurementId: 'G-1CX8DQ11X3',
  );
}
